### ISSUE TITLE
non github jekyll extensions 

### ISSUE THREAD

**Issue by bryanhuntesl** [esl/jekyll-codesync-global#28]
The deployment target for this stuff is github pages - but there seem to be two plugins being used which don't work with github : 

* jekyll-archives
* jekyll-menus

https://pages.github.com/versions/

**Comment by victorldleon** [comment]
- I added jekyll-menus just to see how it works since I'm looking for an alternative to have dynamic menus for each conference.
- The same applies for jekyll-archives I was just testing, I will remove them.

**Comment by bryanhuntesl** [comment]
Cool. Yep was worried you’d built something on top 😬. Thanks for letting me know. 

> On 25 Jul 2020, at 01:36, Victor De León <notifications@github.com> wrote:
> 
> ﻿
> I added jekyll-menus just to see how it works since I'm looking for an alternative to have dynamic menus for each conference.
> The same applies for jekyll-archives I was just testing, I will remove them.
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

-- 


Code BEAM V  
<https://www2.erlang-solutions.com/code-beam-v/2020/emailsig>- 10-11 
September 2020

ElixirConf EU Virtual  
<https://www2.erlang-solutions.com/conferences/ECEUV-oct/2020/emailsig>- 
7-8 October 2020

Code Mesh V 
<https://www2.erlang-solutions.com/conferences/code-mesh-v/2020/emailsig> - 
5-6 November 2020




Erlang Solutions cares about your data and privacy; 
please find all details about the basis for communicating with you and the 
way we process your data in our Privacy Policy 
<https://www.erlang-solutions.com/privacy-policy.html>. You can update your 
email preferences or opt-out from receiving Marketing emails here 
<https://www2.erlang-solutions.com/email-preference?epc_hash=JtO6C7Q2rJwCdZxBx3Ad8jI2D4TJum7XcUWcgfjZ8YY>.

**Comment by bryanhuntesl** [comment]
fixed by https://github.com/esl/jekyll-codesync-global/commit/fe3fa7e0508a2879e4f645ac3a816ca1751b252b
