### ISSUE TITLE
Ewa K needs to decide the list of menu items for old conferences

### ISSUE THREAD

**Issue by bryanhuntesl** [esl/jekyll-codesync-global#76]
List is too long - 

Google sheets doc here listing all possible permutations 

Need signoff to determine just 5 or 6 menu items when generating previous event content

We will lose some small amount of data but there is no getting around the fact it needs to be rationalised in order for Victor to progres

https://docs.google.com/spreadsheets/d/11OWLWp78efQLUDqninJKgcDYrBEaFluF0poiEEpidk8/edit#gid=637125825

**Comment by ewakowalska** [comment]
Programme Committee
Schedule
Speakers
Sponsors
Media
Training
Venue

Testimonials (do not have to be visible on the menu item bar, but would be nice to have this just visible on the website, if there are any testimonials for each conference)
Themes  (do not have to be visible on the menu item bar, but should be visible under the first, main banner)

Each menu item has a different name in different conferences, so sometimes Training is ‘Trainings', other time it is 'training-tutorial', we need to copy-paste all so we have it for all former conferences.
